apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rock-paper-scissors
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: rock-paper-scissors.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rock-paper-scissors
            port:
              number: 80
