apiVersion: v1
kind: Service
metadata:
  name: rock-paper-scissors
  labels:
    app: rock-paper-scissors
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: rock-paper-scissors
  type: NodePort
